### ISSUE TITLE
Project configuration doc: "src" instead of "source"

### ISSUE THREAD

**Issue by bpetetot** [pedronauck/docz-website#15]
In `.doczrc.js` documentation, it seems there is a mistake with `source` property name.

It's not `source` property but `src` property instead. 

Because, in v0.3.3, when I set `source:  './src'` it's not working, but when I set `src: './src'`, it works.

https://github.com/pedronauck/docz-website/blob/64eea671b4ceb428223ab930eec6cdff7c7fe6f7/docs/documentation/pages/project-configuration/index.mdx#L20-L29

**Comment by pedronauck** [comment]
Thanks, I'll fix that now @bpetetot  🙏

**Comment by pedronauck** [comment]
Fix on commit cb881828
